version: "3.9"

services:
  backend:
    build: ./backend/ControleDeAtivos
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build: ./frontend/controle-de-ativos
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
    depends_on:
      - backend
